<div class="box">
    <div class="box-header with-border">
        <!--*************** Title da Pagina ***************-->
        <h3 class="box-title">Title</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
        <!--*************** Fim Title da Pagina ***************-->
    </div>
    <!--*************** Corpo da pagina ***************-->
    <div class="box-body">
        <?php
        /* @var $entity \Application\Entity\Controller */
        if ($this->success) {
            echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">X</button></div>';
        }
        if ($this->error) {
            echo '<div class="alert alert-error">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">X</button></div>';
        }
        ?>

        <div class="table-responsive">
            <div class="box-tools pull-right" style="padding-bottom: 15px;">
                <a class="btn btn-success" href="<?php echo $this->url('controller/inserir') ?>">
                    Novo Registro  <i class="glyphicon glyphicon-plus"></i>
                </a>

            </div>
            <?php
            if ($this->data === NULL) {
                echo 'teste;';
            }
            if ($this->data):
                ?>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Nome 
                            </th>
                            <th>
                                Module
                            </th>
                            <th style="width: 100px">
                                Ação
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->data as $entity) : ?>
                            <tr>
                                <td> <?php echo $entity->getId(); ?>                        </td>
                                <td> <?php echo $entity->getDsController(); ?>              </td>
                                <td> <?php echo ($entity->getIdmodule()) ? $entity->getIdmodule()->getNome() : ' '; ?>              </td>

                                <td>
                                    <a class="btn btn-success" href="<?php
                                    echo $this->url('controller/editar', array(
                                        'controller' => 'controller',
                                        'action' => 'editar',
                                        'id' => $entity->getId()));
                                    ?>">
                                        <i class="glyphicon glyphicon-edit"></i>
                                    </a>
                                    <a class="btn btn-danger" href="<?php
                                    echo $this->url('controller/excluir', array(
                                        'controller' => 'controller',
                                        'action' => 'excluir',
                                        'id' => $entity->getId()));
                                    ?>">
                                        <i class="glyphicon glyphicon-remove"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                    <p>  Nenhum registro encontrado </p>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <!--*************** Fim Corpo da pagina***************-->
</div>