<div class="box">
    <div class="box-header with-border">
        <!--*************** Title da Pagina ***************-->
        <h3 class="box-title">Title</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
        <!--*************** Fim Title da Pagina ***************-->
    </div>
    <!--*************** Corpo da pagina ***************-->
    <div class="box-body">
        <?php
        if ($this->success) {
            echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">X</button></div>';
        }
        if ($this->error) {
            echo '<div class="alert alert-error">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">X</button></div>';
        }
        ?>

        <div class="table-responsive">
            <div class="panel panel-default panel-table">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col col-xs-6 pull-right  text-right">
                            <a class="btn btn-success" href="<?php echo $this->url("$this->router/inserir") ?>">
                                Novo Registro  <i class="glyphicon glyphicon-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <?php if ($this->data): ?>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>
                                        #
                                    </th>
                                    
                                    <th style="width: 100px">
                                        <i class="fa fa-cog"></i>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->data as $entity) : ?>
                                    <tr>
                                        <td> <?php echo $entity->getId(); ?>                        </td>
                                        <td>
                                            <a class="btn btn-success" href="<?= $this->url("$this->router/editar", array(
                                                'controller' => $this->router,
                                                'action'     => 'editar',
                                                'id'         => $entity->getId()));
                                            ?>">
                                                <i class="glyphicon glyphicon-edit"></i>
                                            </a>
                                            
                                            <a class="btn btn-danger" href="<?= $this->url("$this->router/excluir", array(
                                                'controller'  => $this->router,
                                                'action'      => 'excluir',
                                                'id'          => $entity->getId()));
                                            ?>">
                                                <i class="glyphicon glyphicon-remove"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php else: ?>
                            <p>  Nenhum registro encontrado </p>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => "$this->router/paginator")); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--*************** Fim Corpo da pagina***************-->
